### PR TITLE
Test pep8speaks

### PR DESCRIPTION
**Pull request by alimanfoo**
Just to check pep8speaks.

### CODE REVIEW

**Comment by alimanfoo** [comment]
From local run of flake8, I'm expecting:

```
zarr/storage.py:43:101: E501 line too long (140 > 100 characters)
```

**Comment by alimanfoo** [comment]
OK, perfect. cc @jakirkham

**Comment by joshmoore** [comment]
Nice!

**Comment by jakirkham** [comment]
Thanks @alimanfoo :)

**Pull request closed without merging**
