### PR TITLE
Release 2.2.0

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR has minor work to prep the full 2.2.0 release.

TODO:
* [x] Upgrade numcodecs dev dependency
* [x] Update release notes
* [x] AppVeyor and Travis CI passes
* [x] Test coverage to 100% (Coveralls passes)

### CODE REVIEW

**Comment by alimanfoo** [comment]
Just waiting to verify that CI passes with upgraded numcodecs.

**Comment by alimanfoo** [comment]
Running locally getting a couple of doctest failures in the tutorial due to small changes in compression ratios with new c-blosc. Will fix and push.

**Comment by alimanfoo** [comment]
This is good to go.

**Comment by jakirkham** [comment]
Thanks @alimanfoo.

Went ahead and tidied up some merged branches as well. Hope that is ok.

**Comment by alimanfoo** [comment]
Thanks @jakirkham.

**Comment by alimanfoo** [comment]
2.2.0 is on PyPI, conda-forge feedstock PR here: https://github.com/conda-forge/zarr-feedstock/pull/16

**Comment by jakirkham** [comment]
Just saw, thanks. Looks good.

Were you planning to publish the GitHub release? Can see the tag is there, just didn't know if you were planning to mark it as latest (or maybe include notes).

**Comment by alimanfoo** [comment]
Thanks for reminder, I've published the github release.

**Pull request merged**
