### PR TITLE
Rework requirements for pyup.io

### PR DESCRIPTION
**Pull request by alimanfoo**
This PR reworks the requirements to allow for automated management via the PyUP bot. Changes include:

* All indirect requirements have been removed from requirements files.
* Only direct requirements that are imported in the main codebase are pinned and will be tracked by the PyUP bot. These are given in ``requirements_dev*`` files.
* Requirements needed for running tests are removed to ``requirements_test.txt`` and are unpinned to avoid too much noise from PyUP.
* ``pip freeze`` has been added to CI scripts to ensure we can debug exactly what packages were installed into the environment for any given CI run.
* I've also tentatively removed 32-bit windows runs from appveyor to reduce CI overhead. Has been discussed over on numcodecs (https://github.com/zarr-developers/numcodecs/issues/97). Happy to revert this if needs more discussion.

TODO:
* [ ] Changes documented in docs/release.rst
* [ ] Docs build locally (e.g., run ``tox -e docs``)
* [ ] AppVeyor and Travis CI passes
* [ ] Test coverage is 100% (Coveralls passes)

### CODE REVIEW

**Comment by alimanfoo** [comment]
Tests are currently failing on PY37 because numcodecs is not building C extensions, I believe this is because I removed cython from the test environments and so an attempt is being made to build from generate C sources, but in current numcodecs release those are not compatible with PY37. This has been resolved upstream in numcodecs (https://github.com/zarr-developers/numcodecs/pull/92) but that has not been released yet. A workaround is to ensure cython is ensured in the zarr CI environments, so numcodecs gets cythonized during install.

**Comment by alimanfoo** [comment]
OK, CI is green. @zarr-developers/core-devs any objections?

**Comment by jhamman** [comment]
LGTM, nice to see the simplified dev environment.

**Comment by alimanfoo** [comment]
Hm, can't figure out why coveralls has dropped since last commit. Looks like PY2 branches are not getting covered, but the PY2 CI run on travis completed fine.

**Comment by alimanfoo** [comment]
Ah, sorry, there is [one line uncovered](https://coveralls.io/builds/20100666/source?filename=zarr%2Fstorage.py#L1946), looks like it snuck in from #268. Will merge this and deal with that separately.

**Pull request merged**
